- name: First Boot Configuration
  hosts: localhost
  become: yes
  environment:
    DEBIAN_FRONTEND: "noninteractive"
  vars:
    deb_directory: "/slurm-debs/"
    exclude_keywords:
      - slurmdbd
      - slurmctld
      - slurmrestd
    package_list:
      - libpmix-dev
      - libpmix2
      - libopenmpi-dev
      - libopenmpi3
      - openmpi-bin
      - golang
      - rsyslog
      - make
      - wget
      - curl
      - unzip
      - git
      - hwloc
      - libdbus-1-dev
      - locales
      - bash-completion
      - net-tools
      - gnupg
      - lsb-release
      - ca-certificates
      - rsync
      - tzdata
      - tree
      - nano
      - vim
      - tmux
      - jq
      - linux-image-generic
      - linux-headers-generic
      - systemd
      - sudo
      - openmpi-bin
      - kmod
      - numactl
      - htop
      - iftop
      - iotop
      - sysstat
      - lsof
      - strace
      - openssl
      - ethtool
      - iptables-persistent
      - iputils-ping
      - dnsutils
      - traceroute
      - tcpdump
      - apt-utils
      - libnccl2
      - libnccl-dev
      - systemd-sysv
      - dbus
      - pciutils
      - ifupdown
      - netbase
      - ipmitool
      - rdma-core
      - libdbus-1-3
      - gettext
      - pkg-config
      - python3
      - python3-pip
      - python3-venv
      - python3-psutil
      - rrdtool

  tasks:
    - name: Update and upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure required packages are installed
      apt:
        name: "{{ package_list }}"
        update_cache: yes
        cache_valid_time: 3600

