- name: Create Users 
  hosts: localhost
  become: true

  vars:
    username: "wwuser"
    password: "wwpassword"


  tasks:
    - name: Ensure wwuser exists and set password
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        groups: sudo
        append: yes
        shell: /bin/bash
        create_home: yes

